services:
  - type: web
    name: sistema-notas
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: DB_HOST
        value: mainline.proxy.rlwy.net
      - key: DB_NAME
        value: railway
      - key: DB_USER
        value: root
      - key: DB_PASS
        value: XPxgBOZFnQnMCVvLyDhruxubLBTucnDE
      - key: DB_PORT
        value: "33034" 